---
title: My favourite celebrity
hero_image: images/banner.png
description: Create your first website about your favourite celebrity!
duration: 2
technologies: html-css-javascript
software: html-css-javascript
version: 4.0.1
listed: true
copyedit: true
ingredient: false
last_tested: '2019-5-21'
steps:
- title: Introduction
  completion: engaged
- title: Get started
- title: Add style to your web page
- title: 'Challenge: style your heading'
  challenge: true
- title: Show photos on your page
- title: Add YouTube videos to your page
- title: Display a Twitter profile
  completion: internal
- title: Create links to other websites
- title: 'Challenge: more pages'
  challenge: true
