title: My favourite celebrity
hero_image: images/banner.png
description: Create your first website about your favourite celebrity.
version: 4
listed: false
copyedit: false
last_tested: "2018-07-26"
steps:
  - title: Introduction
  - title: What you will need
  - title: Step title
