title: My favourite celebrity
hero_image: images/banner.png
description: Create your first website about your favourite celebrity.
version: 4
listed: false
copyedit: false
ingredient: false
last_tested: "2018-08-02"
steps:
  - title: Introduction
  - title: What you will need
  - title: Getting started
  - title: My first webpage
  - title: Styling our webpage
  - title: Adding images to our webpage
  - title: Embedding YouTube videos in our webpage
  - title: Embedding Twitter profiles in our webpage
  - title: Add links to other websites
  - title: Challenge
